//
//  fakeJSON_Data.swift
//  streamLabs
//
//  Created by Sajjad Sarkoobi on 5/20/19.
//  Copyright © 2019 sarkoobi. All rights reserved.
//

import Foundation

//User name fake JSON data
let userNameFakeJSON = "{\r\n  \"items\": {\r\n    \"users\": [\r\n      {\r\n        \"name\": \"Feed\",\r\n        \"avatar\": \"sampleURL\",\r\n        \"showCounter\": false,\r\n        \"showStar\": false,\r\n        \"counter\": 0\r\n      },\r\n      {\r\n        \"name\": \"$5k Contest\",\r\n        \"avatar\": \"sampleURL\",\r\n        \"showCounter\": false,\r\n        \"showStar\": true,\r\n        \"counter\": 0\r\n      },\r\n      {\r\n        \"name\": \"Sajjad\",\r\n        \"avatar\": \"sampleURL\",\r\n        \"showCounter\": true,\r\n        \"showStar\": false,\r\n        \"counter\": 5\r\n      },\r\n      {\r\n        \"name\": \"Neda\",\r\n        \"avatar\": \"sampleURL\",\r\n        \"showCounter\": true,\r\n        \"showStar\": false,\r\n        \"counter\": 8\r\n      },\r\n      {\r\n        \"name\": \"testing\",\r\n        \"avatar\": \"sampleURL\",\r\n        \"showCounter\": false,\r\n        \"showStar\": false,\r\n        \"counter\": 0\r\n      },\r\n      {\r\n        \"name\": \"testing\",\r\n        \"avatar\": \"sampleURL\",\r\n        \"showCounter\": false,\r\n        \"showStar\": false,\r\n        \"counter\": 0\r\n      },\r\n      {\r\n        \"name\": \"Daniel\",\r\n        \"avatar\": \"sampleURL\",\r\n        \"showCounter\": true,\r\n        \"showStar\": false,\r\n        \"counter\": 2\r\n      },\r\n      {\r\n        \"name\": \"Ali\",\r\n        \"avatar\": \"sampleURL\",\r\n        \"showCounter\": true,\r\n        \"showStar\": false,\r\n        \"counter\": 1\r\n      },\r\n      {\r\n        \"name\": \"testing\",\r\n        \"avatar\": \"sampleURL\",\r\n        \"showCounter\": false,\r\n        \"showStar\": false,\r\n        \"counter\": 0\r\n      },\r\n      {\r\n        \"name\": \"Daniel\",\r\n        \"avatar\": \"sampleURL\",\r\n        \"showCounter\": true,\r\n        \"showStar\": false,\r\n        \"counter\": 2\r\n      },\r\n      {\r\n        \"name\": \"Ali\",\r\n        \"avatar\": \"sampleURL\",\r\n        \"showCounter\": true,\r\n        \"showStar\": false,\r\n        \"counter\": 1\r\n      },\r\n      {\r\n        \"name\": \"$5k Contest\",\r\n        \"avatar\": \"sampleURL\",\r\n        \"showCounter\": false,\r\n        \"showStar\": true,\r\n        \"counter\": 0\r\n      }\r\n    ]\r\n  }\r\n}"


//Fake comments JSON data
let messagesFakeJSON = "{\r\n  \"comments\": {\r\n    \"messages\": [\r\n      {\r\n        \"name\": \"neda\",\r\n        \"message\": \"just like this 200 times!\"\r\n      },\r\n      {\r\n        \"name\": \"sajjad\",\r\n        \"message\": \"👍👍👍👍👍👍\"\r\n      },\r\n      {\r\n        \"name\": \"ali\",\r\n        \"message\": \"such a nice game 🧨🧨🧨🧨🧨!\"\r\n      },\r\n      {\r\n        \"name\": \"gammer110\",\r\n        \"message\": \"☠️ fire it ☠️\"\r\n      },\r\n      {\r\n        \"name\": \"neda\",\r\n        \"message\": \"🇮🇷🇮🇷🇮🇷🇮🇷🇮🇷!\"\r\n      },\r\n      {\r\n        \"name\": \"drjiiiiz\",\r\n        \"message\": \"like it 1000👍!\"\r\n      },\r\n      {\r\n        \"name\": \"neda\",\r\n        \"message\": \"just like this 200 times!\"\r\n      },\r\n      {\r\n        \"name\": \"sajjad\",\r\n        \"message\": \"☠️ fire it ☠️\"\r\n      },\r\n      {\r\n        \"name\": \"ali\",\r\n        \"message\": \"such a nice game 🧨🧨🧨🧨!\"\r\n      },\r\n      {\r\n        \"name\": \"gammer110\",\r\n        \"message\": \"fire it!\"\r\n      },\r\n      {\r\n        \"name\": \"neda\",\r\n        \"message\": \"so nice!\"\r\n      },\r\n      {\r\n        \"name\": \"drjiiiiz\",\r\n        \"message\": \"like it 1000👍!\"\r\n      }\r\n    ]\r\n  }\r\n}"
